export finetuned_model=./checkpoint/model_best
python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 50 \
    --eval_steps 50 \
    --seed 42 \
    --model_name_or_path ./UIE \
    --output_dir $finetuned_model \
    --train_path re_data/train.txt \
    --dev_path re_data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 5 \
    --per_device_train_batch_size  5 \
    --num_train_epochs 20 \
    --learning_rate 5e-6 \
    --label_names "start_positions" "end_positions" \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1 \
    --multilingual False
